name: Build Test and Deploy

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: |
          if npm run | grep -qi "^ *lint"; then
            npm run lint
          else
            echo "No lint script found - skipping"
          fi

      - name: Type check
        run: |
          if [ -f "tsconfig.json" ]; then
            if npm run | grep -qi "^ *type[- ]?check"; then
              npm run type-check
            else
              npx tsc --noEmit
            fi
          else
            echo "No TypeScript config - skipping type check"
          fi

      - name: Run tests
        run: |
          if npm run | grep -qi "^ *test"; then
            npm test
          else
            echo "No test script found - skipping tests"
          fi

      - name: Build SAPience ML Platform
        env:
          NODE_ENV: production
        run: |
          echo "🚀 Building SAPience ML Platform v2.0..."
          npm run build
          echo "✅ Build completed successfully"

      - name: Verify build output
        run: |
          if [ -d ".next" ]; then
            echo "✅ .next directory created successfully"
            echo "Build output size:"
            du -sh .next/ || true
          else
            echo "❌ .next directory not found"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sapience-build-${{ matrix.node-version }}
          path: |
            .next/
            public/
          if-no-files-found: ignore
          retention-days: 3

  test-deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build for test deploy
        run: |
          npm run build
          echo "Test deployment build completed"

      - name: Test deployment (dry run)
        run: |
          echo "✅ Build artifacts ready for deployment"
          echo "📁 Deployment directory: .next/"
          echo "🌍 Would deploy to Netlify preview"
          if [ -d ".next" ]; then
            echo "✅ Build output verified"
          else
            echo "❌ Build output missing"
            exit 1
          fi
