name: Build Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    name: Test Build Process
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Run lint check
      run: npm run lint
      continue-on-error: true
      
    - name: Run type check
      run: npm run type-check
      continue-on-error: true
      
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Test build output
      run: |
        if [ -d ".next" ]; then
          echo "✅ Build successful - .next directory exists"
          ls -la .next/
        else
          echo "❌ Build failed - .next directory not found"
          exit 1
        fi
        
    - name: Build summary
      run: |
        echo "🎉 Build completed successfully!"
        echo "Ready for deployment to Netlify"